language: go

go_import_path: go.spiff.io/codf
go:
  - '1.9'
  - '1.10'
  - tip

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
